import { useState } from 'react';
import Head from 'next/head'
import HomeEventoCard from '../components/HomeEventoCard';
import { FaArrowAltCircleLeft, FaArrowAltCircleRight } from "react-icons/fa";
import Carousel from 'react-bootstrap/Carousel';

export default function Home() {
  const [active, setActive] = useState(0);


  const nextIcon = () => (
    <span><FaArrowAltCircleLeft className="fs-1" /></span>
  )

  return (
    <div>
      <Head>
        <title>Tucuman Turismo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="px-5 py-4 bg-color-2 text-light d-flex justify-content-between">
          <h1 className="fw-bold">CONOCÉ NUESTROS ULTIMOS EVENTOS</h1>
          <a className="btn-touch bg-color-1 d-flex text-light align-items-center justify-content-center col-2 rounded-0 text-decoration-none">
            Ver Todos
          </a>
        </div>
        <div>
          <Carousel className="d-flex"
            nextIcon={
              <span>
                <FaArrowAltCircleRight className="fs-1" />
              </span>
            }
            prevIcon={
              <span>
                <FaArrowAltCircleLeft className="fs-1" />
              </span>
            }
          >
            <Carousel.Item>
              <HomeEventoCard img={"/img/eventos/evento-1.jpg"}></HomeEventoCard>
            </Carousel.Item>
            <Carousel.Item>
              <HomeEventoCard img={"/img/eventos/evento-2.jpg"}></HomeEventoCard>
            </Carousel.Item>
          </Carousel>
        </div>
      </header>
    </div>
  )
}
