import Head from 'next/head'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Tucuman Turismo</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <div className="px-5 py-4 bg-color-2 text-light d-flex justify-content-between">
          <h1 className="fw-bold">CONOCÉ NUESTROS ULTIMOS EVENTOS</h1>
          <a className="btn-touch bg-color-1 d-flex text-light align-items-center justify-content-center col-2 rounded-0 text-decoration-none">
            Ver Todos
          </a>
        </div>
      </header>
    </div>
  )
}
